version: '3.7'

services:
  A:
    image: alpine
    command: |
      sh -c "apk add --no-cache bind-tools curl iputils iptables && \
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE  && \
      tail -f /dev/null"
    privileged: true
    networks:
      custom_network:
        ipv4_address: 10.5.0.2

  B:
    image: alpine
    command: | 
      sh -c "apk add --no-cache bind-tools curl iputils traceroute && \
      ip route del default  && \
      ip route add default via 10.5.0.2 && \
      tail -f /dev/null"

    privileged: true
    networks:
      custom_network:
        ipv4_address: 10.5.0.3

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
