version: "3"
services:
  mitmproxy:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: ["mitmweb", "--mode", "transparent", "--web-host", "0.0.0.0"]
    privileged: true
    ports:
      - "8081:8081"
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
