version: "3"
services:
  mitmproxy:
    build: ./mitm
    container_name: mitmproxy
    cap_add:
      - NET_ADMIN
    command:
      [
        "mitmweb",
        "--mode",
        "transparent",
        "--web-host",
        "0.0.0.0",
      ]
    ports:
      - "8081:8081"
    networks:
      mitm-net:
        ipv4_address: 10.121.0.2
    sysctls:
      net.ipv4.ip_forward: 1
  client:
    build: ./client
    container_name: mitmproxy-client
    cap_add:
      - NET_ADMIN
    depends_on:
      - mitmproxy
    networks:
      mitm-net:
        ipv4_address: 10.121.0.3

networks:
  mitm-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.121.0.0/16
